import { Heart, Megaphone, MessageCircle, Pin } from "lucide-react";
import { createAnnouncementAction } from "@/app/actions";
import { Card, EmptyState, SectionHeader } from "@/components/ui/base";
import { fmtDate, relativeTime } from "@/lib/format";
import { repo } from "@/lib/repo";
import { AnnouncementBadge, getManageContext } from "../../_components/manage-ui";
import { SubmitButton } from "../../_components/SubmitButton";

export const metadata = { title: "עדכונים" };

export default async function Page(){
 const {session}=await getManageContext(); const announcements=(await repo.getAnnouncementsByBuilding(session.buildingId)).sort((a,b)=>Number(b.pinned)-Number(a.pinned)||b.date.localeCompare(a.date));
 return <div className="space-y-5"><section className="fade-up"><h1 className="text-3xl font-black tracking-tight">עדכונים לקהילה</h1><p className="mt-1 text-sm text-muted">פרסום הודעות ועד, תחזוקה, כספים ואירועים לכל הדיירים.</p></section><Card className="fade-up p-4"><SectionHeader title="פרסום הודעה" /><form action={createAnnouncementAction} className="space-y-3"><label><span className="label">כותרת</span><input name="title" className="input" required placeholder="למשל: ניתוק מים מתוכנן" /></label><label><span className="label">תוכן</span><textarea name="body" className="textarea" rows={4} required placeholder="הודעה מקצועית וברורה לדיירים" /></label><div className="grid grid-cols-2 gap-3"><label><span className="label">קטגוריה</span><select name="category" className="select"><option value="general">כללי</option><option value="maintenance">תחזוקה</option><option value="urgent">דחוף</option><option value="event">אירוע</option><option value="finance">כספים</option></select></label><label className="flex items-end gap-2 rounded-2xl bg-surface-2 p-3 text-sm font-bold"><input type="checkbox" name="pinned" /> נעוץ בראש</label></div><SubmitButton>פרסם עדכון</SubmitButton></form></Card><section className="fade-up"><SectionHeader title="הודעות קיימות" />{announcements.length ? <div className="space-y-3">{announcements.map(a=><Card key={a.id} className="p-4" as="article"><div className="flex items-center justify-between gap-3"><AnnouncementBadge category={a.category}/>{a.pinned && <span className="inline-flex items-center gap-1 text-xs font-bold text-brand"><Pin size={13}/> נעוץ</span>}</div><h2 className="mt-3 text-lg font-black">{a.title}</h2><p className="mt-2 whitespace-pre-line text-sm leading-6 text-muted">{a.body}</p><div className="mt-4 flex items-center justify-between border-t border-border pt-3 text-xs text-muted"><span>{a.author} · {fmtDate(a.date)} · {relativeTime(a.date)}</span><span className="flex items-center gap-3"><span className="inline-flex items-center gap-1"><Heart size={14}/> {a.reactions}</span><span className="inline-flex items-center gap-1"><MessageCircle size={14}/> {a.comments}</span></span></div></Card>)}</div> : <EmptyState icon={<Megaphone size={24}/>} title="אין הודעות" sub="פרסמו הודעה ראשונה לדיירים." />}</section></div>
}
